# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title


lang: en
timezone: Europe/Zagreb

title: Duško Simidžija
tagline: Self Rubber Ducking
github:
  username: dsimidzija

social:
  name: Dusko Simidzija
  email: dusko.simidzija@gmail.com
  links:
    - https://dsimidzija.github.io
    - https://github.com/dsimidzija
    - https://www.linkedin.com/in/duskosimidzija

theme: jekyll-theme-chirpy
theme_mode: dark
avatar: images/avatar-v1.png
markdown: kramdown
highlighter: rouge

excerpt_separator: <a name="excerpt-continue"></a>

google_analytics:
  id: "G-B0MLF9E0DR"

toc: true

assets:
  self_host:
    enabled: true

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - .rbenv-version
  - .rvmrc
  - README.md
  - Rakefile
  - node_modules
  - tools

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: https://dsimidzija.github.io
